highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: "https://www.example.com/" # Required: replace this with your domain
name: textalic # Required: will be displayed on every page's header
title: site title # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - one liner one...
  - one liner two...
description: "Some short description on your site" # Required

disqus: # Optional
  shortname:  # Add your disqus shortname here
  comments: on # Global toggle on/off disqus feature

google_analytics: # Optional
  id: "" # Replace with your google analytics tracking id

collections: # Define post series here
  demo_series:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"